version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  registries:
  - npm-registry-npm-pkg-github-com
